<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-HvacController-bead0476-d2ca-4d9a-a4b0-758216be02be</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Iot.Device.Bindings" Version="4.2.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.9" />
    <PackageReference Include="MQTTnet" Version="5.1.0.1559" />
    <PackageReference Include="System.Device.Gpio" Version="4.2.0" />
  </ItemGroup>
</Project>
